### PR TITLE
Added javafx to gradle builde file.

### PR DESCRIPTION
**Pull request by Huskydog9988**
Helps fix any issues in the event the person building doesn't have javafx "in the right place."

All credit goes to @aTom3333 for actually writing these changes.

(Tried adding him co-author feature, though he hasn't shown up on the commit, which I suspect means he needs to accept it. Haven't used it before so I have no clue.)

### CODE REVIEW

**Comment by alexhliu** [comment]
This actually breaks when I try to build with the error:
```
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by aTom3333** [comment]
This is the same problem we have in main chunky, the plug-in has to be used conditionally based on the version of the jdk used to build. I think jackjt8 had a go at it but without success

**Comment by Huskydog9988** [comment]
I was about to ask about jdk versions. I haven't changed this since my last build and it has built just fine since I added these lines.

**Comment by jackjt8** [comment]
This patch works fine for JDK11+. It is not compatible with JDK8 even if we add a check to ignore it.

**Pull request closed without merging**
